### ISSUE TITLE
MacOS `install` does not provide -D option

### ISSUE THREAD

**Issue by ATLowther** [chuck-flowers/git-gossip#2]
MacOS options are seen here: https://ss64.com/osx/install.html

I believe the equivalent as assumed by the `Makefile`, `ginstall`, can be accessed through `coreutils`: https://formulae.brew.sh/formula/coreutils

**Comment by chuck-flowers** [comment]
The version of `install` provided by macOS based on the documentation provided seems to behave very differently from the version provided by the GNU coreutils. I'll likely rewrite the Makefile to use `mkdir -p` before the install command which would allow for dropping the `-D` flag.

**Comment by chuck-flowers** [comment]
@ATLowther can you confirm [https://github.com/chuck-flowers/git-gossip/pull/4](this PR) fixes the issue for the macOS environement?

**Comment by ATLowther** [comment]
> @ATLowther can you confirm [https://github.com/[/pull/4](https://github.com/chuck-flowers/git-gossip/pull/4)](this PR) fixes the issue for the macOS environement?

This did resolve the issue with allowing me to run `make` without it throwing an error. I did however get this as part of my output, `/bin/sh: pandoc: command not found`. It appears to have still built and no error was thrown. It might be worth adding that in to the README as a dependency as well.

**Comment by chuck-flowers** [comment]
The `pandoc` dependency is already mentioned in the README under the **From Source** section.

**Comment by ATLowther** [comment]
> The `pandoc` dependency is already mentioned in the README under the **From Source** section.

Why yes it is. Should `make` fail without it? I can start a PR for an explicit dependency check before trying to execute the other targets

**Comment by chuck-flowers** [comment]
So `pandoc` is used to generated the man pages from mark down files. If you want to avoid the man page generation, you could run `make executables && sudo make install-executables` to only build and install the executable portion. Generally speaking, I think man pages for an application are essential so they should be part of a default installation.
