### ISSUE TITLE
Unable to execute `git gossip`

### ISSUE THREAD

**Issue by ATLowther** [chuck-flowers/git-gossip#3]
Prior to running `make` a modification was made to the `Makefile` to use `ginstall` on MacOS 12.2.1., which supports the `-D` flag, 3 instances of `install` were replaced with `ginstall`:

1. executables: $(DST_BIN_DIR)/$(BIN_NAME)
  $(DST_BIN_DIR)/$(BIN_NAME): $(SRC_BIN_DIR)/$(BIN_NAME)
	  $(SHELLCHECK) $(SHELLCHECK_FLAGS) $^
	  ginstall -D $^ $@
2. install-executables:
	ginstall -Dm555 $(DST_BIN_DIR)/$(BIN_NAME) -t $(PREFIX)/bin
3. install-man-pages:
	ginstall -Dm444 $(wildcard $(DST_MAN_DIR)/*.1.gz) -t $(PREFIX)/share/man/man1

After following the README instructions and running `git gossip init` in the root directory of a project it yields:

`fatal: 'gossip' appears to be a git command, but we were not able to execute it. Maybe git-gossip is broken?`

**Comment by chuck-flowers** [comment]
Hey @ATLowther, can you run the following commands and include the related output.

```bash
which git-gossip
ls -al $(which git gossip)
```
The commands above should ensure that git-gossip is available on the system's `PATH` and that the permissions of the script are appropriately set.

**Comment by ATLowther** [comment]
> 

```console
user@machine dir % which git-gossip
/Users/user/.local/bin/git-gossip
```

```console
user@machine dir % ls -al $(which git gossip)
ls: found: No such file or directory
ls: gossip: No such file or directory
ls: not: No such file or directory
```

**Comment by chuck-flowers** [comment]
My mistake. For the second line I meant for you to run:
```bash
ls -al $(which git-gossip)
```

**Comment by ATLowther** [comment]
> My mistake. For the second line I meant for you to run:
> 
> ```shell
> ls -al $(which git-gossip)
> ```

```console
user@machine dir % ls -al $(which git-gossip)
-r-xr-xr-x  1 user  staff  1230 Mar  4 20:46 /Users/user/.local/bin/git-gossip
```

**Comment by chuck-flowers** [comment]
What happens if you run `git-gossip init` instead of `git gossip init`

**Comment by ATLowther** [comment]
> 

> What happens if you run `git-gossip init` instead of `git gossip init`

This was it. The result was:
`zsh: /Users/user/.local/bin/git-gossip: bad interpreter: /usr/bin/bash: no such file or directory`

My OS didn't ship with a `bash` executable at that path; updating the `git-gossip` script to look instead at the path of `/bin/bash` now allows me to utilize `git gossip` per the documentation.

**Comment by chuck-flowers** [comment]
Okay, I'll likely switch the shebang to be `/bin/bash` which will work on my distribution of Linux as well. Another alternative would be `/bin/env bash`. Does the `/bin/env` executable exist within the macOS environment?

**Comment by chuck-flowers** [comment]
I'm closing this issue out as well. The shebang is now `#!/usr/bin/env bash` which seems to be the most portable shebang available
